spring.cloud.gateway.server.webflux.routes[0].id=employee
spring.cloud.gateway.server.webflux.routes[0].uri=lb://employee
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employee/**

spring.cloud.gateway.server.webflux.routes[1].id=department
spring.cloud.gateway.server.webflux.routes[1].uri=lb://department
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/department/**

spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=employee
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/employee
 
 // for Employee
resilience4j.circuitbreaker.instances.employee.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.employee.slidingWindowSize=6
resilience4j.circuitbreaker.instances.employee.failureRateThreshold=50
resilience4j.circuitbreaker.instances.employee.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.employee.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.employee.minimumNumberOfCalls=5

spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=department
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/department
 
// Department 
resilience4j.circuitbreaker.instances.department.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.department.slidingWindowSize=6
resilience4j.circuitbreaker.instances.department.failureRateThreshold=50
resilience4j.circuitbreaker.instances.department.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.department.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.department.minimumNumberOfCalls=5


management.endpoints.web.exposure.include=*

 
